### ISSUE TITLE
Error: Interface Filter does not have constructors

### ISSUE THREAD

**Issue by ghost** [Giszmo/NostrPostr#2]
> Get [Android Studio](https://developer.android.com/studio/) for free
Clone this repository
Import it in Android Studio
[Create an Android Virtual Device](https://developer.android.com/studio/run/managing-avds)
Launch the app (That "play" button top left)

I followed these steps from readme and getting an error:

```
\NostrPostr\app\src\main\java\nostr\postr\MainActivity.kt: (49, 22): Interface Filter does not have constructors
```
![image](https://user-images.githubusercontent.com/94559964/181763794-5d68a172-f83f-4ea6-a8c4-eec39485b462.png)

**Comment by Giszmo** [comment]
Thanks for reporting. The android app is not much of a nostr client yet. It merely uses a bit the lib I ended up focusing on but now you can see how the app starts and spams logcat with nostr events.

With latest commit this issue should be fixed.
